import React from "react";
const columns = [
  {name: "ID", uid: "id", sortable: true},
  {name: "RANK", uid: "rank", sortable: true},
  {name: "DEVELOPER", uid: "developer", sortable: true},
  {name: "STREAK_COUNT", uid: "streak_count", sortable: true},
  {name: "TOTAL_CONTRIBUTION", uid: "total_contribution", sortable: true},
  {name: "EMAIL", uid: "email"},
];

const users = [
  {
    id: 1,
    rank: "1",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    rank: "2",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    rank: "3",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    rank: "4",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    rank: "5",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    rank: "6",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "brian.kim@example.com",
    status: "Active",
  },
  {
    id: 7,
    rank: "7",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    rank: "8",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    rank: "9",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    rank: "10",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "emma.adams@example.com",
  },
  {
    id: 11,
    rank: "11",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "brandon.stevens@example.com",
  },
  {
    id: 12,
    rank: "12",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?img=10",
    email: "megan.richards@example.com",
  },
  {
    id: 13,
    rank: "13",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "oliver.scott@example.com",
  },
  {
    id: 14,
    rank: "14",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?img=16",
    email: "grace.allen@example.com",
  },
  {
    id: 15,
    rank: "15",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?img=15",
    email: "noah.carter@example.com",
  },
  {
    id: 16,
    rank: "1",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?img=20",
    email: "ava.perez@example.com",
  },
  {
    id: 17,
    rank: "17",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?img=33",
    email: "liam.johnson@example.com",
  },
  {
    id: 18,
    rank: "18",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?img=29",
    email: "sophia.taylor@example.com",
  },
  {
    id: 19,
    rank: "19",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?img=50",
    email: "lucas.harris@example.com",
  },
  {
    id: 20,
    rank: "20",
    developer: "Tony Reichert",
    streak_count: "29",
    total_contribution: "300",
    avatar: "https://i.pravatar.cc/150?img=45",
    email: "mia.robinson@example.com",
  },
];

export {columns, users,};
